tasks:
  - init: |
      echo 'init OK'
    command: |
      echo 'command OK'
      python -m http.server 8000

ports:
  - name: site
    description: Página principal
    port: 8000
    onOpen: open-browser
