tasks:
  - init: |
      echo 'init OK'
  -  command: |
      echo 'command OK'
      python -m http.server 8000

ports:
  - name: Site
    description: Página principal
    port: 8000
    visibility: public
    onOpen: open-browser

  - name: Game
    description: Jogo usando server em Node.js
    port: 3000
    visibility: public
    onOpen: open-browser  
