tasks:
  - init: |
      echo 'TODO: build project OK'
    command: |
      echo 'TODO: start app OK'

ports:
  - name: Site
    description: Página principal
    port: 8000
    visibility: public
    onOpen: open-browser

  - name: Game
    description: Jogo usando server em Node.js
    port: 3000
    visibility: public
    onOpen: open-browser  
