tasks:
  - init: |
      echo 'TODO: build project OK'
    command: |
      echo 'TODO: start app OK'

ports:
  - name: Site
    description: Página principal
    port: 8000
    visibility: public
    onOpen: open-browser