tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      python -m http.server 8000
      echo 'TODO: start app'

ports:
  - port: 8000
    onOpen: open-preview
    visibility: public
